// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetHealthcheckParams creates a new GetHealthcheckParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetHealthcheckParams() *GetHealthcheckParams {
	return &GetHealthcheckParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetHealthcheckParamsWithTimeout creates a new GetHealthcheckParams object
// with the ability to set a timeout on a request.
func NewGetHealthcheckParamsWithTimeout(timeout time.Duration) *GetHealthcheckParams {
	return &GetHealthcheckParams{
		timeout: timeout,
	}
}

// NewGetHealthcheckParamsWithContext creates a new GetHealthcheckParams object
// with the ability to set a context for a request.
func NewGetHealthcheckParamsWithContext(ctx context.Context) *GetHealthcheckParams {
	return &GetHealthcheckParams{
		Context: ctx,
	}
}

// NewGetHealthcheckParamsWithHTTPClient creates a new GetHealthcheckParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetHealthcheckParamsWithHTTPClient(client *http.Client) *GetHealthcheckParams {
	return &GetHealthcheckParams{
		HTTPClient: client,
	}
}

/* GetHealthcheckParams contains all the parameters to send to the API endpoint
   for the get healthcheck operation.

   Typically these are written to a http.Request.
*/
type GetHealthcheckParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get healthcheck params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHealthcheckParams) WithDefaults() *GetHealthcheckParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get healthcheck params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHealthcheckParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get healthcheck params
func (o *GetHealthcheckParams) WithTimeout(timeout time.Duration) *GetHealthcheckParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get healthcheck params
func (o *GetHealthcheckParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get healthcheck params
func (o *GetHealthcheckParams) WithContext(ctx context.Context) *GetHealthcheckParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get healthcheck params
func (o *GetHealthcheckParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get healthcheck params
func (o *GetHealthcheckParams) WithHTTPClient(client *http.Client) *GetHealthcheckParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get healthcheck params
func (o *GetHealthcheckParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetHealthcheckParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
