// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/UnoHouse/api/swagger/models"
)

// GetHealthcheckReader is a Reader for the GetHealthcheck structure.
type GetHealthcheckReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHealthcheckReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetHealthcheckOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetHealthcheckBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetHealthcheckInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetHealthcheckOK creates a GetHealthcheckOK with default headers values
func NewGetHealthcheckOK() *GetHealthcheckOK {
	return &GetHealthcheckOK{}
}

/* GetHealthcheckOK describes a response with status code 200, with default header values.

OK
*/
type GetHealthcheckOK struct {
}

func (o *GetHealthcheckOK) Error() string {
	return fmt.Sprintf("[GET /healthcheck][%d] getHealthcheckOK ", 200)
}

func (o *GetHealthcheckOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetHealthcheckBadRequest creates a GetHealthcheckBadRequest with default headers values
func NewGetHealthcheckBadRequest() *GetHealthcheckBadRequest {
	return &GetHealthcheckBadRequest{}
}

/* GetHealthcheckBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetHealthcheckBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *GetHealthcheckBadRequest) Error() string {
	return fmt.Sprintf("[GET /healthcheck][%d] getHealthcheckBadRequest  %+v", 400, o.Payload)
}
func (o *GetHealthcheckBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetHealthcheckBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetHealthcheckInternalServerError creates a GetHealthcheckInternalServerError with default headers values
func NewGetHealthcheckInternalServerError() *GetHealthcheckInternalServerError {
	return &GetHealthcheckInternalServerError{}
}

/* GetHealthcheckInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetHealthcheckInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *GetHealthcheckInternalServerError) Error() string {
	return fmt.Sprintf("[GET /healthcheck][%d] getHealthcheckInternalServerError  %+v", 500, o.Payload)
}
func (o *GetHealthcheckInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetHealthcheckInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
